name: Playwright Tests

on:
  push:
    branches: [ main, preview ]
  pull_request:
    branches: [ main, preview ]
  workflow_dispatch:
    inputs:
        browser:
            type: choice
            description: Which browser engine(s) to test?
            required: true
            options:
            - all browser engines
            - chromium
            - firefox
            - webkit

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        # run: npx playwright test
        run: npx playwright test --project ${{ github.event.inputs.browser || 'chromium' }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
            name: playwright-report
            path: playwright-report/
            retention-days: 30




      # Uncomment and configure the following if you need a SQL Server service for integration tests
      # - name: Set up SQL Server
      #   uses: azure/sql-action@v2
      #   with:
      #     connection-string: ${{ secrets.SQL_CONNECTION_STRING }}
      #     # Add additional setup as needed
